version: '3.4'

services:
  infomatemind:
    image: infomatemind
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - ollama
    ports:
      - 8000:8000

  ollama:
    image: ollama/ollama:0.5.11
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    environment:
      - MODEL_NAME=deepseek-r1:1.5b
